// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cfP1P8H-RuyNMHVLkDPIwZNyrXg3Sm8',
    appId: '1:570254434318:web:770807f2ac674c4707dc5f',
    messagingSenderId: '570254434318',
    projectId: 'fitness-gym-app-6024f',
    authDomain: 'fitness-gym-app-6024f.firebaseapp.com',
    storageBucket: 'fitness-gym-app-6024f.appspot.com',
    measurementId: 'G-6DR626PHVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyO28TNn3PhGvrbQBvV_a72o5bkTNJu6g',
    appId: '1:570254434318:android:bf1e976f060a021b07dc5f',
    messagingSenderId: '570254434318',
    projectId: 'fitness-gym-app-6024f',
    storageBucket: 'fitness-gym-app-6024f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5dqgNFl_K11oemw42Mi13HQp6pR2Lsk',
    appId: '1:570254434318:ios:fce42b6e5d5522e107dc5f',
    messagingSenderId: '570254434318',
    projectId: 'fitness-gym-app-6024f',
    storageBucket: 'fitness-gym-app-6024f.appspot.com',
    iosClientId: '570254434318-gpjhnknagnpci7oplrd3kpte3g1bgovu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessUiKit',
  );
}
